#!/bin/sh

set -e
set -x

DEVICE=${DEVICE-nexus_5}
MODE=${MODE-Release}

platform_tools/android/bin/adb_push_if_needed resources/ /data/local/tmp/resources &
platform_tools/android/bin/adb_push_if_needed skps/ /data/local/tmp/skps &
platform_tools/android/bin/android_ninja -d $DEVICE -t $MODE $1 &
wait

time platform_tools/android/bin/android_run_skia -d $DEVICE -t $MODE $@ -i /data/local/tmp/resources --skps /data/local/tmp/skps
