#!/usr/bin/env python
#coding=utf-8

import sys

a = {}
b = {}

for (path, d) in [(sys.argv[1], a), (sys.argv[2], b)]:
  for line in open(path):
    try:
      time, label = line.split()
      d[label] = float(time)
    except:
      pass

common = set(a.keys()).intersection(b.keys())

def safe_divide(x, y):
  if y == 0:
    if x == 0:
      return 1
    return float('inf')
  return x/y

total_b, total_a = 0, 0
ratio_products = 1.0
minimum = float('inf')
maximum = 0
for label in common:
  total_b += b[label]
  total_a += a[label]
  ratio = safe_divide(a[label], b[label])
  minimum = min(ratio, minimum)
  maximum = max(ratio, maximum)
  if ratio != float('inf'):
      ratio_products *= ratio
  print '%3.1fx %s %g %g' % (ratio, label, a[label], b[label])

mean = safe_divide(total_a, total_b)
geomean = ratio_products ** (1.0 / len(common))
print 'summary: ≥%3.1fx (A %3.1fx, G %3.1fx) ≤%3.1fx' % (
        minimum, mean, geomean, maximum)
