#!/usr/bin/env python

import sys

a = {}
b = {}

for (path, d) in [(sys.argv[1], a), (sys.argv[2], b)]:
  for line in open(path):
    try:
      time, label = line.split()
      d[label] = float(time)
    except:
      pass

common = set(a.keys()).intersection(b.keys())

def safe_divide(x, y):
  if y == 0:
    if x == 0:
      return 1
    return float('inf')
  return x/y

for label in common:
  print '%.2g %s %g %g' % (b[label]/a[label], label, a[label], b[label])

