#!/bin/sh

set -e

./gyp_skia >/dev/null
ninja -C out/Debug dump_record >/dev/null

out/Debug/dump_record -r $@ --timeWithCommand > no-opt.log
out/Debug/dump_record -O -r $@ --timeWithCommand > opt.log

git diff --no-index --word-diff no-opt.log opt.log
