#!/bin/sh

set -e

./gyp_skia >/dev/null
ninja -C out/Debug dump_record >/dev/null

out/Debug/dump_record -r $@ > no-opt.log
out/Debug/dump_record -O -r $@ > opt.log

git diff --no-index no-opt.log opt.log
