#!/bin/sh

set -x
set -e

diskutil erasevolume HFS+ "RAM" `hdiutil attach -nomount ram://41943040`

mkdir /Volumes/RAM/ccache
mkdir /Volumes/RAM/skia_out
mkdir /Volumes/RAM/chromium_out

rm -rf ~/.ccache
rm -rf ~/skia/out
rm -rf ~/chromium/src/out

ln -s /Volumes/RAM/ccache ~/.ccache
ln -s /Volumes/RAM/skia_out ~/skia/out
ln -s /Volumes/RAM/chromium_out ~/chromium/src/out
