#!/usr/bin/env python

import sys

record, playback = {}, {}
for line in open(sys.argv[1]):
    try:
        tokens  = line.split()
        samples = tokens[:-1]
        label   = tokens[-1]
        name, ext = label.split('.')

        d = record if ext == 'skp' else playback
        d[name] = map(float, samples)
    except:
        pass

def summarize(label, d):
    g = 1
    for name in record:
        g *= min(*d[name]) / 1000
    print label, int(g ** (1.0 / len(d)))

summarize('record', record)
summarize('playback', playback)
