#!/usr/bin/env python

import sys

def fill(path, r, p):
    for line in open(path):
        try:
            tokens  = line.split()
            samples = tokens[:-1]
            label   = tokens[-1]
            name, ext = label.split('.')

            d = r if ext == 'skp' else p
            d[name] = map(float, samples)
        except:
            pass

br, bp = {}, {}
fill(sys.argv[1], br, bp)

record, playback = {}, {}
fill(sys.argv[2], record, playback)

def summarize(b, d, metric=min):
    g = 1
    sb = 0
    sd = 0
    for name in record:
        g *= metric(*d[name]) / metric(*b[name])
        sb += metric(*b[name])
        sd += metric(*d[name])
    geo = g ** (1.0 / len(d))
    arith = sd/sb

    err = 0
    for name in record:
        err += (metric(*d[name]) / metric(*b[name]) - arith)**2
    var = err / (len(d) - 1)

    noise = (var ** 0.5) / arith

    return geo, arith, noise


def percent(f):
    return '%d%%' % int(f * 100)

print map(percent, summarize(br, record)), map(percent, summarize(bp, playback))
